# Generated by Django 5.1.3 on 2024-12-10 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_precio_base_modelo_precio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='anio',
            new_name='año',
        ),
    ]
